### PR TITLE
Test on Windows with AppVeyor

### PR DESCRIPTION
**Pull request by briandfoy**
I went through a bunch of MANIFEST.SKIP files to add _.appveyor.yml_ entries, so I figured I should add it to this module (which already has one for Travis). Along the way I added an AppVeyor config. I [already have it passing](https://ci.appveyor.com/project/briandfoy/extutils-manifest/build/1.0.3) as my fork.

Someone would need to set up an organization account on AppVeyor or test it through organization membership with their individual account, but that's no big whoop.

### CODE REVIEW

**Comment by karenetheridge** [comment]
> Someone would need to set up an organization account on AppVeyor or test it through organization membership with their individual account, but that's no big whoop.

Last time I looked into it, it didn't look easy -- it required making some security changes to my github account that weren't clearly explained, and some other things that weren't well-documented.  Do you have a guide for what is necessary?

**Comment by briandfoy** [comment]
I think I'd simply create a role account on github and add it to the
Toolchain group. That "user" can then subscribe to Travis or AppVeyor. How
are you doing Travis now?

If it's too weird for anyone else to set up, someone can add me to the
Toolchain org and I'll test it from my AppVeyor account.

I don't remember making any changes to my GitHub account. I log into
AppVeyor and everything was there. The Toolchain org might have other
restrictions.


-- 
brian d foy <brian.d.foy@gmail.com>
http://www.pair.com/~comdog/

**Comment by haarg** [comment]
I have the Perl-Toolchain-Gang user and PerlToolchainGang project on AppVeyor.  The project is meant to grant access to members of the Github Perl-Toolchain-Gang org, but that may not be working right now.  I can manually grant access though if anyone creates an account on AppVeyor.

I created this repo on AppVeyor, but I don't have permission to enable the hooks on Github for this repo.

**Comment by Leont** [comment]
> I created this repo on AppVeyor, but I don't have permission to enable the hooks on Github for this repo.

I do have those permissions, but it isn't clear to me how to enable it to the PerlToolchainGang project on AppVeyor :-/

**Comment by haarg** [comment]
I've granted @Leont admin access to the AppVeyor project.  Hopefully that will work.

AppVeyor can grant access to GitHub teams, which I attempted to use before.  But the team that I used for that doesn't appear to exist anymore.

**Comment by karenetheridge** [comment]
merged, thanks! let's see what appveyor.com thinks now :)

**Pull request closed without merging**
